variable "compartment_id" {}
variable "datascience_project_description" {}
variable "datascience_project_display_name" {}
variable "datascience_model_display_name" {}
variable "datascience_model_deployment_display_name" {}
variable "datascience_model_deployment_shape" {}
variable "datascience_notebook_session_is_deployed" {}
variable "datascience_notebook_session_display_name" {}
variable "datascience_notebook_session_shape" {}
variable "datascience_notebook_session_ocpu" {}
variable "datascience_notebook_session_memory_in_gb" {}
variable "datascience_notebook_session_block_storage_size_in_gbs" {}
